### ISSUE TITLE
Kann die App nicht starten 

### ISSUE THREAD

**Issue by viktorowich** [SharedKnowledge/SharkNet#1]
Folgende Fehlermeldung: 
Error:A problem occurred configuring project ':app'.

> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
> Could not find com.github.SharedKnowledge:SharkFW-Android:-SNAPSHOT.
>      Required by:
>          SharkNet:app:unspecified > com.github.SharedKnowledge:SharkNet-Api-Android:-SNAPSHOT

**Comment by j4rvis** [comment]
Hey Viktor,

jitpack macht uns da scheinbar nur Probleme..
Ich werde erst ende der Woche wenn nicht sogar erst nächste Woche dazu kommen das anzupassen.
Versuch einen älteren Commit der api zu nutzen.

**Comment by viktorowich** [comment]
Ich werde es versuchen zu umgehen.

**Comment by j4rvis** [comment]
Habe den Bug nun gelöst indem ich die komplette struktur überarbeitet habe. In der README findest du die notwendigen Schritte. Wichtig ist, dass das SharkFW auf deinem Rechner installiert sein muss mit maven. Die anderen repositories sind mittels submodulen eingebunden. Die Kommandos findest du im README. Schreib mir wenn etwas nicht funktioniert.
